files:
  include: 'src/scss/**/*.s+(a|c)ss'
  ignore: ''

rules:
  class-name-format:
    - 0

  clean-import-paths:
    - 0

  force-attribute-nesting:
    - 0

  force-element-nesting:
    - 0

  force-pseudo-nesting:
    - 0

  leading-zero:
    - 1

  max-file-line-count:
    - 1
    - length: 600

  no-color-literals:
    - 0

  no-important:
    - 1

  no-url-domains:
    - 0

  no-url-protocols:
    - 0

  no-vendor-prefixes:
  - 1
  -
    excluded-identifiers:
      - webkit
      - moz

  property-sort-order:
    - 1
    - order: smacss

  placeholder-in-extend:
    - 0
